feat: reactive `availableLocales` using computed property
intlify/vue-i18n pull request #2058
Opened 2024-12-27 11:12 UTC by mnenie

resolves #1893 

so, I had the same problem and as a solution I implemented the idea suggested by the man who created the issue using `computed` in `availableLocales` at `composer.ts`
also I wrote some tests and change some things in `legacy.ts` to accommodate this of course
now its works great :)

2024-12-27 23:55 UTC, kazupon commented on packages/vue-i18n-core/test/legacy.test.ts
> +  test('reactive update', () => {
It is necessary to test with `watch` / `watchEffect` to see if the reaction is taking place.

2024-12-27 23:56 UTC, kazupon requested changes
Thank you for your contributing!
I've just reviewed your PR!
Please, let's check it out :)

2024-12-28 13:26 UTC, mnenie commented
> Thank you for your contributing! I've just reviewed your PR! Please, let's check it out :)

hi @kazupon !
so, I made it
I hope that's what you asked for 💯 :)

2024-12-28 13:38 UTC, BobbieGoede commented
Just checking, this would be a breaking change right?

2024-12-28 13:49 UTC, mnenie commented
> Just checking, this would be a breaking change right?

maybe yea
so, now we have a reactive scenario with `availableLocales ` and the type of usage will change to `.value` in `setup`

2024-12-29 01:01 UTC, kazupon commented
@BobbieGoede 
> Just checking, this would be a breaking change right?

Thank you for making me realize!
Yeah, This PR has breaking changes.
So, I've made `v11` branch.
https://github.com/intlify/vue-i18n/tree/v11

v11 branch will be included bug fixes and backward-compatible features until vue-i18n v12
`master` branch is v12 develop branch.

2024-12-31 05:56 UTC, kazupon approved these changes

2024-12-31 05:56 UTC, merged